# -*- coding: utf-8 -*-
"""CNNLSTM.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bCmVixA79y23SCeSGROqMXbPT0P65QL-
"""

from google.colab import drive
drive.mount('/content/drive')

import os   
import pickle 
import numpy as np
from tqdm.notebook import tqdm 

from keras.applications.vgg16 import VGG16 , preprocess_input 
from keras.utils import load_img, img_to_array
from keras.preprocessing.text import Tokenizer
from keras.utils import pad_sequences
from keras.models import Model
from keras.utils import to_categorical, plot_model
from keras.layers import Input,Dense,LSTM, Embedding, Dropout, add

imgPath = ('/content/drive/MyDrive/Project/Images')
txtPath = ('/content/drive/MyDrive/Project/captions.txt')

model = VGG16()


model = Model(inputs = model.inputs , outputs = model.layers[-2].output)

print(model.summary())

features = {}
directory = '/content/drive/MyDrive/Project/Images'

for img_name in tqdm(os.listdir(directory)):
    img_path = directory + '/' + img_name
    image = load_img(img_path, target_size=(224, 224))
    # pixeller numpy dizisine çevrilir
    image = img_to_array(image)
    image = image.reshape((1, image.shape[0], image.shape[1], image.shape[2]))
    # preprocess işlemi / vgg16 için
    image = preprocess_input(image)
    # özellik çıkarımı
    feature = model.predict(image, verbose=0)
    image_id = img_name.split('.')[0]
    features[image_id] = feature

WORKING_DIR = '/content/drive/MyDrive/Project'

pickle.dump(features, open(os.path.join(WORKING_DIR, 'features.pkl'), 'wb'))

WORKING_DIR = '/content/drive/MyDrive/Project'

with open(os.path.join(WORKING_DIR, 'features.pkl'), 'rb') as f:
    features = pickle.load(f)

txt_directory = '/content/drive/MyDrive/Project/captions.txt'
with open(os.path.join(txt_directory), 'r') as f:
    next(f)
    captions_doc = f.read()

mapping = {}
for line in tqdm(captions_doc.split('\n')):
    # cümleleri ayırıyoruz
    tokens = line.split(',')
    if len(line) < 2:
        continue
    image_id, caption = tokens[0], tokens[1:]
    # uzantı kısmını id den kaldırıyoruz
    image_id = image_id.split('.')[0]
    caption = " ".join(caption)
    # liste
    if image_id not in mapping:
        mapping[image_id] = []

    mapping[image_id].append(caption)

len(mapping)

def clean(mapping):
    for key, captions in mapping.items():
        for i in range(len(captions)):
            # tek seferde 1 caption alıyoruz
            caption = captions[i]
            caption = caption.lower()
            caption = caption.replace('[^A-Za-z]', '')
            # fazla boşlukları kaldırma
            caption = caption.replace('\s+', ' ')
            caption = 'startseq ' + " ".join([word for word in caption.split() if len(word)>1]) + ' endseq'
            captions[i] = caption

def clean(mapping):
    for key, captions in mapping.items():
        for i in range(len(captions)):
            caption = captions[i]
            caption = caption.lower()
            caption = caption.replace('[^A-Za-z]', '')
            caption = caption.replace('\s+', ' ')
            caption = 'startseq ' + " ".join([word for word in caption.split() if len(word)>1]) + ' endseq'
            captions[i] = caption

# metin önişlemeden önce
mapping['1000268201_693b08cb0e']

clean(mapping)

# temizleme işleminden sonra
mapping['1000268201_693b08cb0e']

all_captions = []
for key in mapping:
    for caption in mapping[key]:
        all_captions.append(caption)

len(all_captions)

all_captions[:10]

tokenizer = Tokenizer()
tokenizer.fit_on_texts(all_captions)
vocab_size = len(tokenizer.word_index) + 1

vocab_size

max_length = max(len(caption.split()) for caption in all_captions)
max_length

image_ids = list(mapping.keys())
split = int(len(image_ids) * 0.80)
train = image_ids[:split]
test = image_ids[split:]

def data_generator(data_keys, mapping, features, tokenizer, max_length, vocab_size, batch_size):
    X1, X2, y = list(), list(), list()
    n = 0
    while 1:
        for key in data_keys:
            n += 1
            captions = mapping[key]
  
            for caption in captions:
                # encode input sequence
                seq = tokenizer.texts_to_sequences([caption])[0]
                # split the sequence into X, y pairs
                for i in range(1, len(seq)):
                    # split into input and output pairs
                    in_seq, out_seq = seq[:i], seq[i]
                    # pad input sequence
                    in_seq = pad_sequences([in_seq], maxlen=max_length)[0]
                    # encode output sequence
                    out_seq = to_categorical([out_seq],num_classes=vocab_size)[0]
                    
                    X1.append(features[key][0])
                    X2.append(in_seq)
                    y.append(out_seq)
            if n == batch_size:
                X1, X2, y = np.array(X1), np.array(X2), np.array(y)
                yield [X1, X2], y
                X1, X2, y = list(), list(), list()
                n = 0

# encoder model

# image
inputs1 = Input(shape=(4096,))
fe1 = Dropout(0.4)(inputs1)
fe2 = Dense(256, activation='relu')(fe1)

# sequence
inputs2 = Input(shape=(max_length,))
se1 = Embedding(vocab_size, 256, mask_zero=True)(inputs2)
se2 = Dropout(0.4)(se1)
se3 = LSTM(256)(se2)

# decoder model
decoder1 = add([fe2, se3])
decoder2 = Dense(256, activation='relu')(decoder1)
outputs = Dense(vocab_size, activation='softmax')(decoder2)

model = Model(inputs=[inputs1, inputs2], outputs=outputs)
model.compile(loss='categorical_crossentropy', optimizer='adam')

plot_model(model, show_shapes=True)

epochs = 15
batch_size = 8
steps = len(train) // batch_size

for i in range(epochs):
    generator = data_generator(train, mapping, features, tokenizer, max_length, vocab_size, batch_size)
    model.fit(generator, epochs=1, steps_per_epoch=steps, verbose=1)

model.save(WORKING_DIR+'/best_model5.h5')

def idx_to_word(integer, tokenizer):
    for word, index in tokenizer.word_index.items():
        if index == integer:
            return word
    return None

def predict_caption(model, image, tokenizer, max_length):
    in_text = 'startseq'
    # iterasyonumuzu max uzunluk kadar döndürüyoruz
    for i in range(max_length):
        # girdi dizisi
        sequence = tokenizer.texts_to_sequences([in_text])[0]
        # pad_sequences sabit uzunluk sağlamak için
        sequence = pad_sequences([sequence], max_length)
        # sonraki kelimenin tahmin edilmesi aşaması
        yhat = model.predict([image, sequence], verbose=0)
        # olasılığı yüksek olan indeksi alırız
        yhat = np.argmax(yhat)
        #index - word dönüşümü
        word = idx_to_word(yhat, tokenizer)
        if word is None:
            break
        # bir sonraki kelimeyi oluşturmak için kelimeyi girdi olarak ekliyoruz.
        in_text += " " + word
        if word == 'endseq':
            break
    return in_text

BASE_DIR ='/content/drive/MyDrive/Project'

from nltk.translate.bleu_score import corpus_bleu
# test verileri ile doğrulama işlemi gerçekleştiriyoruz.
actual, predicted = list(), list()

for key in tqdm(test):
    # gerçek başlık
    captions = mapping[key]
    # tahmin edilen başlık
    y_pred = predict_caption(model, features[key], tokenizer, max_length)
    # split işlemi ile kelimelere bölüyoruz
    actual_captions = [caption.split() for caption in captions]
    y_pred = y_pred.split()
    # gerçek ve tahmin edilen başlıkları ayrı ayrı listeliyoruz.
    actual.append(actual_captions)
    predicted.append(y_pred)
# BLEU hesaplanması
print("BLEU-1: %f" % corpus_bleu(actual, predicted, weights=(1.0, 0, 0, 0)))
print("BLEU-2: %f" % corpus_bleu(actual, predicted, weights=(0.5, 0.5, 0, 0)))

from PIL import Image
import matplotlib.pyplot as plt
def generate_caption(image_name):
    image_id = image_name.split('.')[0]
    img_path = os.path.join(BASE_DIR, "Images", image_name)
    image = Image.open(img_path)
    captions = mapping[image_id]
    print('---------------------Actual---------------------')
    for caption in captions:
        print(caption)
    y_pred = predict_caption(model, features[image_id], tokenizer, max_length)
    print('--------------------Predicted--------------------')
    print(y_pred)
    plt.imshow(image)

generate_caption("1001773457_577c3a7d70.jpg")

generate_caption("1002674143_1b742ab4b8.jpg")

generate_caption("101669240_b2d3e7f17b.jpg")